---

- name: Clone a repo with separate git directory
  git:
      repo: https://github.com/nick1846/jenkins-docker-compose.git
      dest: /home/ec2-user/webhost

- name: Make sure compose service is up
  docker_compose:
      project_src: /home/ec2-user/webhost
      pull: yes
      files:
            - docker-compose.yml
      state: present
